### ISSUE TITLE
Base root is not defined / types.php is not writable

### ISSUE THREAD

**Issue by bezin** [lukaskleinschmidt/kirby-types#1]
Hi Lukas, 

thanks for this plugin. I wanted to try it out, but when I run `kirby types:create` it fails due to `/types.php` not being writable. This path made me suspicious and as far as I gathered from the code, [the path should have been prepended](https://github.com/lukaskleinschmidt/kirby-types/blob/main/src/Types.php#L123) with the Kirby `base` root. I have this root set up in my `index.php` but apparently these are ignored by Kirby  CLI and `base` [does not seem to be a default root](https://github.com/getkirby/kirby/blob/282b1e25faa0bc24c903237a7484dc45fa475c36/src/Cms/Core.php#L293-L321)? When I run `kirby roots` it also does not list a `base` root.

Any idea what might be the issue? I don't have much experience with the Kirby 3 CLI, but I am happy to provide more information. Just let me know. 

Best

Edit: The Kirby version used is `3.9.2`

**Comment by lukaskleinschmidt** [comment]
I was not aware that the `base` is actually just used used/mentioned for the [public folder setup](https://getkirby.com/docs/guide/configuration#custom-folder-setup__public-folder-setup). I think having it along the lines of `$this->app->root('base') ?? $this->app->root('index')` should fix that. I will push a fix for that

**Comment by lukaskleinschmidt** [comment]
Please let me know if that works
